name: sqlite_ai
version: 0.7.59
description: >
  SQLite-AI is an extension for SQLite that brings artificial intelligence
  capabilities directly into the database. It enables developers to run,
  fine-tune, and serve AI models from within SQLite using simple SQL queries â€”
  ideal for on-device and edge applications where low-latency and offline
  inference are critical.
homepage: https://github.com/sqliteai/sqlite-ai
repository: https://github.com/sqliteai/sqlite-ai

environment:
  sdk: ^3.10.0

dependencies:
  code_assets: ^1.0.0
  hooks: ^1.0.0
  path: ^1.8.0
  sqlite3: ^3.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
